version: "3.9"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - chemotion_db:/var/lib/postgresql/data/
    networks:
      - chemotion

  # This module contains Wine to make .exe files work in Linux.
  # Antivirus may complain and is an optional module, so it can be left commented out
  # More about it in this issue: https://github.com/ComPlat/chemotion_ELN/issues/1331
  msconvert:
    image: ptrxyz/chemotion:msconvert-1.8.2
    restart: unless-stopped
    hostname: msconvert
    volumes:
      - spectra:/shared:rw
    networks:
      - chemotion

  spectra:
    image: ptrxyz/chemotion:spectra-1.8.2
    restart: unless-stopped
    hostname: spectra
    volumes:
      - spectra:/shared:rw
    depends_on:
      - msconvert
    networks:
      - chemotion

  worker:
    image: ptrxyz/chemotion:eln-1.8.2
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=worker
      - SECRET_KEY_BASE=pleasechangeme
    depends_on:
      - db
      - eln
      - spectra
    volumes:
      - chemotion_data:/chemotion/data/
      - chemotion:/chemotion/app
    networks:
      - chemotion

  eln:
    image: ptrxyz/chemotion:eln-1.8.2
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=eln
      - SECRET_KEY_BASE=pleasechangeme
    depends_on:
      - db
      - spectra
    volumes:
      - eln_pullin:/shared
      - eln_backup:/backup
      - chemotion_data:/chemotion/data/
      - chemotion:/chemotion/app
    ports:
      - 4000:4000
    networks:
      - chemotion

  ketchersvc:
    image: ptrxyz/chemotion:ketchersvc-1.8.2
    restart: unless-stopped
    environment:
      - CONFIG_KETCHER_URL=http://eln:4000/ketcher/
    init: true
    depends_on:
      eln:
        condition: service_healthy
    networks:
      - chemotion

  converter:
    image: ptrxyz/chemotion:converter-1.8.2
    restart: unless-stopped
    environment:
      - SECRET_KEY=imsupersecretandwanttobechanged
    volumes:
      - converter_profiles:/srv/chemotion/profiles
      - converter_datasets:/srv/chemotion/datasets
    networks:
      - chemotion

volumes:
  chemotion:
    name: chemotion_app
  chemotion_data:
    name: chemotion_data
  chemotion_db:
    name: chemotion_db
  spectra:
    name: chemotion_spectra
  eln_pullin:
    name: eln_pullin
  eln_backup:
    name: eln_backup
  converter_datasets:
    name: converter_datasets
  converter_profiles:
    name: converter_profiles

networks:
  chemotion: